### ISSUE TITLE
Java command fails on Windows machines

### ISSUE THREAD

**Issue by lvkv** [garimpeiro-it/node-key-sender#17]
Using this in an electron app - this executes the jar file using single quotes in the command, which fails on Windows machines

**Comment by eynol** [comment]
Same error. However, It seems that the problem was resolved 7 months ago. You can change your local `key-sender.js`  with this [line](https://github.com/garimpeiro-it/node-key-sender/blob/01a99ca8c7cfecd8fdb807f57535b4fd81de36c1/key-sender.js#L115) . 
This module should be updated on npmjs.com. @fernandohu

**Comment by lvkv** [comment]
Gotcha. Thanks for the info!
