### ISSUE TITLE
"Error: Unable to access jarfile" if spaces in folder name (with fix)

### ISSUE THREAD

**Issue by heyheyjc** [garimpeiro-it/node-key-sender#9]
Windows 10, Node 8.10.0, webdriverio
The fix is to use double quotes not escaped single quotes in key-sender.js Line 115:

_Instead of:_
var command = 'java -jar \'' + jarPath + '\' ' + arrParams.join(' ') + module.getCommandLineOptions();

_Use:_
var command = 'java -jar "' + jarPath + '" ' + arrParams.join(' ') + module.getCommandLineOptions();

**Comment by Enteleform** [comment]
Had the same issue, can confirm that @heyheyjc's fix works.

**Comment by legekka** [comment]
Same issue, same fix. Maybe a platform check would be nice there.

**Comment by nmynarcik** [comment]
Hey guys, instead of making another "unable to access jar" issue, I wanted to piggy back here.

I have a similar issue. It's not a space in the file name, but I still get the same error. When using the path it's reporting in the error directly in cmd, it works, but when the node app tries, it fails. Any idea on how to get this working?

**Comment by ikovac** [comment]
it works.
